### ISSUE TITLE
missing include files for xdmf version 2 and 3

### ISSUE THREAD

**Issue by fbordeu** [lhofmann/paraview-superbuild-docker#1]
Hello,

My plugin uses files for the xdmf2 and xdmf3, but not all the includes files (*.h, and hpp) are in the container.  I tried to copy the missings files using "docker cp ..." from the source but some files are generated at compilation time. Here is an example of my compilation error inside the container:
  
[  5%] Building CXX object Plugin/PXDMFReader/CMakeFiles/PXDMFReader.dir/vtkPXDMFDocument.cxx.o
In file included from /home/paraview/buildbuildbuildbuildbuildbuildbuildbuildbuildbuildbuildbuildbuildbuild/install/include/paraview-5.8/vtkxdmf3/XdmfGrid.hpp:28,
                 from /mnt/PXDMFTools/Plugin/PXDMFReader/XDMF3Data.h:25,
                 from /mnt/PXDMFTools/Plugin/PXDMFReader/vtkPXDMFDocument.cxx:52:
/home/paraview/buildbuildbuildbuildbuildbuildbuildbuildbuildbuildbuildbuildbuildbuild/install/include/paraview-5.8/Xdmf.hpp:131:10: fatal error: XdmfConfig.hpp: No such file or directory
 #include "XdmfConfig.hpp"
          ^~~~~~~~~~~~~~~~
compilation terminated.

I'm going to try to build my own images and try to correct the error, but I'm not expert in docker....

The missing files are store or generated from 

ParaView/VTK/ThirdParty/xdmf3/vtkxdmf3/core/
ParaView/VTK/ThirdParty/xdmf2/vtkxdmf2/libsrc

Felipe

**Comment by lhofmann** [comment]
Did you copy `Xdmf.hpp` into the container yourself? I don't see this file in my containers and `XdmfConfig.hpp` is also not referenced in any file of `vtkxdmf3`. 
These two files are missing, but it seems to me like this is done on purpose by VTK, as they are also missing when doing a regular build. You could open an issue at [VTK](https://gitlab.kitware.com/vtk/vtk/-/issues) about this.

Here are the contents of the generated files that you are missing (they are generated but not installed):

 `vtkxdmf3/XdmfConfig.hpp` 
```cpp
#ifndef XDMFCONFIG_HPP_
#define XDMFCONFIG_HPP_

#define BUILD_SHARED
#ifndef BUILD_SHARED
#  define XDMFSTATIC
#endif

#endif
```

`vtkxdmf3/core/XdmfCoreConfig.hpp` 
```cpp
#ifndef XDMFCORECONFIG_HPP_
#define XDMFCORECONFIG_HPP_

/* #undef HAVE_BOOST_SHARED_DYNAMIC_CAST */
/* #undef XDMF_BIG_ENDIAN */

#define BUILD_SHARED
#ifndef BUILD_SHARED
#  define XDMFSTATIC
#endif

#define XDMF_NO_REALPATH

#endif /* XDMFCORECONFIG_HPP_ */
```
