### ISSUE TITLE
ParaView 5.11.0 Support

### ISSUE THREAD

**Issue by majksner** [lhofmann/paraview-superbuild-docker#2]
I have tried to compile a new version of ParaView by modifying `build.sh` but it crashes, unfortunately.

Have you had a chance to try it out?

**Comment by lhofmann** [comment]
Hi,

This project is deprecated in favor of the Kitware-supported docker images at [kitware/paraview_org-plugin-devel](https://hub.docker.com/r/kitware/paraview_org-plugin-devel).

**Comment by majksner** [comment]
I am sorry I did not know that. Thank you for pointing out.
